name: ci

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  x86_64-linux-gnu:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@v6
        with:
          persist-credentials: false
      - uses: https://github.com/mlugg/setup-zig@v2.2.1
        with:
          # version: master
          version: 0.16.0-dev.2736+3b515fbed
          # version: 0.16.0-dev.2565+684032671
          # mirror: https://ziglang.freetls.fastly.net
      - name: Deps
        run: |
          apt update
          apt install -y wayland-protocols libwayland-client0 pkg-config libwayland-dev
      - name: Build
        run: zig build -Dtarget=x86_64-linux-gnu -Doptimize=ReleaseSafe --summary all
